name: WS Cleanup Tool - Master
on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  schedule:
    - cron: '0 4 * * 6'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      TOOL_NAME: projects_cleanup
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Set Environment Variables
        run: |
          echo "TOOL_DIR=ws_$TOOL_NAME" >> $GITHUB_ENV
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=$(echo ${{github.ref}} |  sed -r 's/^[\/a-zA-z-]+//')" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
      - uses: UnicornGlobal/trufflehog-actions-scan@master
        with:
          branch: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 wheel
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E501,F841
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Unittesting
        run: python -m unittest
      - name: Create Wheel Package
        run: python setup.py bdist_wheel
      - name: Install Wheel package
        run: ls -1 dist/*.whl | xargs pip install
      - name: Full Test
        run: python ./projects_cleanup/cleanup_tool.py ./projects_cleanup/params_ci.config ${{ secrets.WS_USER_KEY }} ${{ secrets.WS_ORG_TOKEN }}
      - name: Publish to Test PyPI
        if: startsWith(github.ref, 'refs/tags/test-v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
      - name: Zip release
        uses: papeloto/action-zip@v1
        with:
          files: requirements.txt LICENSE README.md CLA.md ${{ env.TOOL_DIR }}/
          dest: ws_$TOOL_NAME.zip
          recursive: true
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: "*.zip"
      - name: confluence-markdown-sync
        if: startsWith(github.ref, 'refs/tags/v')
        uses: cupcakearmy/confluence-markdown-sync@v1     
        with: 
          from: README.md
          to: 1864533094
          cloud: whitesource
          user: ${{ secrets.CONFLUENCE_USER }}
          token: ${{ secrets.CONFLUENCE_TOKEN }}
      - name: confluence-markdown-sync
        if: startsWith(github.ref, 'refs/tags/v')
        uses: cupcakearmy/confluence-markdown-sync@v1     
        with: 
          from: README.md
          to: 2319614065
          cloud: whitesource
          user: ${{ secrets.CONFLUENCE_USER }}
          token: ${{ secrets.CONFLUENCE_TOKEN }}
